const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const ADD_QUANTITY = 'ADD_QUANTITY';
const SUB_QUANTITY = 'SUB_QUANTITY';
const EMPTY_CART = 'EMPTY_CART';
const GET_SHOPPING_CART_LIST = 'GET_SHOPPING_CART_LIST';
const REMOVE_SHOPPING_CART_ITEM = 'REMOVE_SHOPPING_CART_ITEM';

export {
  ADD_TO_CART,
  REMOVE_FROM_CART,
  ADD_QUANTITY,
  SUB_QUANTITY,
  EMPTY_CART,
  GET_SHOPPING_CART_LIST,
  REMOVE_SHOPPING_CART_ITEM,
};
